import XCTest
final class MewUITests:XCTestCase {
    func launch(reset:Bool=true,large:Bool=false,dark:Bool=false)->XCUIApplication {let app=XCUIApplication();app.launchArguments=["-mew-ui-test"]+(reset ? ["-mew-reset"]:[])+(large ? ["-mew-large-type"]:[])+(dark ? ["-mew-dark"]:[]);app.launch();XCTAssertTrue(app.buttons["quick-add"].waitForExistence(timeout:30));return app}
    func capture(_ name:String,_ app:XCUIApplication){let a=XCTAttachment(screenshot:app.screenshot());a.name=name;a.lifetime = .keepAlways;add(a)}
    func clear(_ field:XCUIElement,_ app:XCUIApplication,_ value:String){field.tap();let old=field.value as? String ?? "";if old.range(of:"^[0-9.]+$",options:.regularExpression) != nil {field.typeText(String(repeating:XCUIKeyboardKey.delete.rawValue,count:old.count))};field.typeText(value)}
    func tapTab(_ name:String,_ app:XCUIApplication){app.tabBars.buttons[name].tap()}
    func testExpenseEditNavigationAnalyticsAndPersistence(){let app=launch();capture("home-light",app);app.buttons["quick-add"].tap();let amount=app.textFields["amount"];XCTAssertTrue(amount.waitForExistence(timeout:10));amount.tap();amount.typeText("43.21");XCTAssertTrue(app.buttons["save"].isHittable);capture("expense-keyboard",app);app.buttons["save"].tap();XCTAssertTrue(app.buttons["quick-add"].waitForExistence(timeout:10));tapTab("عمليات",app);XCTAssertTrue(app.staticTexts["سجل العمليات"].waitForExistence(timeout:10));let edit=app.buttons.matching(NSPredicate(format:"identifier BEGINSWITH 'edit-'")).firstMatch;XCTAssertTrue(edit.waitForExistence(timeout:10));edit.tap();clear(app.textFields["amount"],app,"50.00");app.buttons["save"].tap();XCTAssertTrue(app.buttons["quick-add"].waitForExistence(timeout:10));capture("transactions",app);tapTab("تحليل",app);XCTAssertTrue(app.buttons["analysis-comparison"].waitForExistence(timeout:10));app.buttons["analysis-comparison"].tap();capture("analytics-comparison",app);tapTab("الخطة",app);XCTAssertTrue(app.buttons["edit-plan"].waitForExistence(timeout:10));capture("plan",app);tapTab("المزيد",app);app.buttons["more-settings"].tap();XCTAssertTrue(app.buttons["theme-dark"].waitForExistence(timeout:10));app.buttons["theme-dark"].tap();tapTab("الرئيسية",app);capture("home-dark",app);app.terminate();let reopened=launch(reset:false);tapTab("عمليات",reopened);XCTAssertTrue(reopened.staticTexts.containing(NSPredicate(format:"label CONTAINS '50.00'")).firstMatch.waitForExistence(timeout:10));capture("persisted-after-relaunch",reopened)}
    func testLargeTypeEntryAndScreens(){let app=launch(large:true,dark:true);let add=app.buttons["quick-add"];XCTAssertGreaterThanOrEqual(add.frame.height,44);capture("large-home",app);add.tap();let field=app.textFields["amount"];XCTAssertTrue(field.waitForExistence(timeout:10));field.tap();field.typeText("١٢.٣٤");capture("large-keyboard",app);let save=app.buttons["save"];XCTAssertTrue(save.isHittable);save.tap();XCTAssertTrue(app.buttons["quick-add"].waitForExistence(timeout:10));tapTab("تحليل",app);capture("large-analytics",app);tapTab("المزيد",app);capture("large-more",app)}
}
