import SwiftUI
struct EditorFrame<Content:View>:View {
    let title:String;let save:()->Void;@ViewBuilder var content:Content
    @Environment(\.dismiss) var dismiss;@EnvironmentObject var store:Store
    var body:some View { NavigationStack { ScrollView { VStack(alignment:.leading,spacing:16){ content }.padding(16) }.scrollDismissesKeyboard(.interactively).navigationTitle(title).navigationBarTitleDisplayMode(.inline).toolbar { ToolbarItem(placement:.cancellationAction){Button("إلغاء"){dismiss()}.disabled(store.busy)};ToolbarItemGroup(placement:.keyboard){Spacer();Button("تم"){UIApplication.shared.sendAction(#selector(UIResponder.resignFirstResponder),to:nil,from:nil,for:nil)}} }.safeAreaInset(edge:.bottom,spacing:0){SaveFooter(title:"حفظ",action:save)}.interactiveDismissDisabled(store.busy) }
}
struct TransactionEditor:View {
    @EnvironmentObject var store:Store;@Environment(\.dismiss) var dismiss
    let h:Household;let route:EditorRoute;let id:String;let original:Transaction?;let feeId:String
    @State var type:TxType;@State var amount:String;@State var date:String;@State var account:String;@State var destination:String;@State var category:String;@State var payment:String;@State var note:String;@State var fee="0";@State var details=false;@State var error:String?;@State var saveTemplate=false;@State var templateTitle="";@State var duplicate=false;@State var pending:Transaction?;@State var pendingFee:Int64=0
    init(h:Household,route:EditorRoute) {
        self.h=h;self.route=route
        let editing=route.kind=="transaction" ? route.transaction:nil
        let refund=route.kind=="refund" ? route.transaction:editing.flatMap{t in h.transactions.first{$0.id==t.originalId}}
        original=refund;id=editing?.id ?? uid(); feeId=uid()
        let initial:TxType=refund != nil ? .refund:editing?.type ?? (route.kind=="income" ? .income:route.kind=="transfer" ? .transfer:.expense)
        _type=State(initialValue:initial);_amount=State(initialValue:editing.map{Finance.input($0.amount)} ?? route.template.map{Finance.input($0.amount)} ?? route.due.map{Finance.input(h.remaining($0))} ?? "")
        _date=State(initialValue:editing?.date ?? Dates.today());let a=editing?.accountId ?? route.template?.accountId ?? h.prefs.defaultAccount ?? h.accounts.first{!$0.archived}?.id ?? "";_account=State(initialValue:a)
        _destination=State(initialValue:editing?.destinationId ?? h.accounts.first{!$0.archived && $0.id != a}?.id ?? "")
        _category=State(initialValue:refund?.categoryId ?? editing?.categoryId ?? route.template?.categoryId ?? route.due?.categoryId ?? h.categories.first{!$0.archived && $0.income==(initial == .income)}?.id ?? "")
        _payment=State(initialValue:editing?.payment ?? "نقد");_note=State(initialValue:editing?.note ?? route.template?.note ?? route.due?.title ?? "");_details=State(initialValue:editing != nil || route.due != nil || refund != nil)
    }
    var body:some View { EditorFrame(title:type == .refund ? "استرداد مصروف":"تسجيل عملية",save:prepare) {
        if let error{Text(error).foregroundStyle(.red).accessibilityIdentifier("form-error")}
        if let original{Hint("المصروف الأصلي: "+Finance.format(original.amount)+" • "+original.date)}
        FormField(label:"المبلغ — جنيه",text:$amount,number:true,identifier:"amount")
        if original==nil && route.due==nil { Picker("النوع",selection:$type){ForEach([TxType.expense,.income,.transfer]){Text($0.title).tag($0)}}.pickerStyle(.segmented).accessibilityIdentifier("type") }
        Picker("الحساب",selection:$account){ForEach(h.accounts.filter{!$0.archived || $0.id==account}){Text($0.name).tag($0.id)}}.accessibilityIdentifier("account")
        if type == .transfer { Picker("الحساب المستلم",selection:$destination){ForEach(h.accounts.filter{!$0.archived && $0.id != account}){Text($0.name).tag($0.id)}};FormField(label:"رسوم التحويل — جنيه",text:$fee,number:true);Hint("الرسوم تُسجل مصروفًا مستقلًا؛ التحويل نفسه لا يدخل في الإنفاق") }
        else if original==nil && route.due==nil { Picker("التصنيف",selection:$category){ForEach(h.categories.filter{(!$0.archived || $0.id==category) && $0.income==(type == .income)}){Text($0.name).tag($0.id)}}.accessibilityIdentifier("category") }
        DisclosureGroup("تفاصيل إضافية",isExpanded:$details){FormField(label:"التاريخ YYYY-MM-DD",text:$date,identifier:"date");FormField(label:"الملاحظة",text:$note,identifier:"note");Picker("طريقة الدفع",selection:$payment){ForEach(["نقد","بطاقة","محفظة","تحويل","أخرى"],id:\.self){Text($0).tag($0)}};if [.expense,.income].contains(type){Toggle("حفظ كقالب سريع",isOn:$saveTemplate);if saveTemplate{FormField(label:"اسم القالب",text:$templateTitle)}} }
    }.onChange(of:type){_,t in category=h.categories.first{!$0.archived && $0.income==(t == .income)}?.id ?? ""}.alert("عملية مشابهة موجودة",isPresented:$duplicate){Button("حفظ عملية مستقلة"){commit()};Button("مراجعة",role:.cancel){pending=nil}}message:{Text("نفس اليوم والحساب والتصنيف والمبلغ. هل هي عملية مستقلة؟")}
    }
    func prepare(){ do { let value=try Finance.money(amount);try require(value>0,"المبلغ أكبر من صفر");_ = try Dates.parse(date)
        let t=Transaction(id:id,type:type,amount:value,date:date,accountId:account,destinationId:type == .transfer ? destination:nil,categoryId:type == .transfer ? nil:category,payment:payment,note:String(note.prefix(500)),originalId:type == .refund ? original?.id:nil,dueId:route.due?.id ?? route.transaction?.dueId)
        var next=store.data ?? h;next.transactions.removeAll{$0.id==id};next.transactions.append(t);_ = try next.validated();if saveTemplate{try require(!templateTitle.trimmingCharacters(in:.whitespaces).isEmpty && templateTitle.count<=60,"أدخل اسم قالب لا يتجاوز 60 حرفًا")};pending=t;pendingFee=type == .transfer ? try Finance.money(fee):0
        if next.transactions.contains(where:{$0.id != id && $0.type==t.type && $0.amount==t.amount && $0.date==t.date && $0.accountId==t.accountId && $0.categoryId==t.categoryId}) {duplicate=true}else{commit()}
    } catch {self.error=error.localizedDescription;details=true} }
    func commit(){guard let t=pending else{return};Task{let template=saveTemplate && [.expense,.income].contains(t.type) ? QuickTemplate(title:templateTitle,type:t.type,amount:t.amount,accountId:t.accountId,categoryId:t.categoryId!,note:t.note):nil;if await store.save(t,fee:pendingFee,feeId:feeId,template:template){dismiss()}else{error=store.message}}}
}
struct SetupView:View {
    @EnvironmentObject var store:Store
    @State var name="النقد";@State var opening="0";@State var salaryDay=25;@State var start=Dates.today();@State var error:String?
    var body:some View {NavigationStack{Page{Cat(size:100);Text("أهلًا بك في Mew").font(.largeTitle.bold());Hint("ابدأ بحسابك وتاريخ المتابعة. لا يوجد اتصال ببنك أو رفع بيانات للخادم.");FormField(label:"اسم أول حساب",text:$name,identifier:"setup-name");FormField(label:"الرصيد الافتتاحي — جنيه",text:$opening,number:true,identifier:"setup-opening");FormField(label:"بدء المتابعة YYYY-MM-DD",text:$start);Stepper("يوم بداية الدورة: \(salaryDay)",value:$salaryDay,in:1...31);if let error{Text(error).foregroundStyle(.red)};Button("ابدأ المتابعة"){do{let value=try Finance.money(opening);Task{_ = await store.change{h in let a=Account(name:name,opening:value);h.accounts.append(a);h.prefs=Preferences(ready:true,salaryDay:salaryDay,trackingStart:start,defaultAccount:a.id)}}}catch{self.error=error.localizedDescription}}.buttonStyle(.borderedProminent).accessibilityIdentifier("setup-save")}.navigationTitle("Mew")}}
}
struct AccountEditor:View {
    @EnvironmentObject var store:Store;@Environment(\.dismiss) var dismiss;let h:Household;let editing:Account?
    @State var name:String;@State var kind:String;@State var opening:String;@State var error:String?
    init(h:Household,editing:Account?=nil){self.h=h;self.editing=editing;_name=State(initialValue:editing?.name ?? "");_kind=State(initialValue:editing?.kind ?? "نقد");_opening=State(initialValue:editing.map{Finance.input($0.opening)} ?? "0")}
    var body:some View {EditorFrame(title:"حساب أو محفظة",save:{do{let value=try Finance.money(opening);let a=Account(id:editing?.id ?? uid(),name:name.trimmingCharacters(in:.whitespaces),kind:kind,opening:value,archived:editing?.archived ?? false);Task{if await store.change(transform:{h in h.accounts.removeAll{$0.id==a.id};h.accounts.append(a)}){dismiss()}}}catch{error=error.localizedDescription}}){FormField(label:"اسم الحساب",text:$name,identifier:"account-name");Picker("النوع",selection:$kind){ForEach(["نقد","بنك","بطاقة","محفظة"],id:\.self){Text($0).tag($0)}};FormField(label:"الرصيد الافتتاحي — جنيه",text:$opening,number:true);Hint("الرصيد الافتتاحي لا يُحسب دخلًا. تعديل قيمته يغيّر رصيد الحساب.");if let error{Text(error).foregroundStyle(.red)}}}
}
struct RuleEditor:View {
    @EnvironmentObject var store:Store;@Environment(\.dismiss) var dismiss;let h:Household;let editing:BillRule?
    @State var title:String;@State var amount:String;@State var category:String;@State var start:String;@State var interval:Int;@State var end:String;@State var error:String?
    init(h:Household,editing:BillRule?=nil){self.h=h;self.editing=editing;_title=State(initialValue:editing?.title ?? "");_amount=State(initialValue:editing.map{Finance.input($0.amount)} ?? "");_category=State(initialValue:editing?.categoryId ?? "expense-1");_start=State(initialValue:editing?.start ?? Dates.today());_interval=State(initialValue:editing?.intervalMonths ?? 1);_end=State(initialValue:editing?.end ?? "")}
    var body:some View {EditorFrame(title:"فاتورة أو قسط",save:save){FormField(label:"العنوان",text:$title);FormField(label:"المبلغ — جنيه",text:$amount,number:true);Picker("التصنيف",selection:$category){ForEach(h.categories.filter{!$0.income && !$0.archived}){Text($0.name).tag($0.id)}};FormField(label:"أول استحقاق YYYY-MM-DD",text:$start);Stepper("كل \(interval) شهر",value:$interval,in:1...12);FormField(label:"آخر استحقاق اختياري YYYY-MM-DD",text:$end);Hint("يظل يوم الاستحقاق الأصلي محفوظًا في الشهور القصيرة. لا تُسجل الفاتورة مصروفًا إلا عند السداد.");if let error{Text(error).foregroundStyle(.red)}}}
    func save(){do{let r=BillRule(id:editing?.id ?? uid(),title:title,amount:try Finance.money(amount),categoryId:category,start:start,intervalMonths:interval,end:end.isEmpty ? nil:end,active:editing?.active ?? true);Task{if await store.change(transform:{h in h.rules.removeAll{$0.id==r.id};h.rules.append(r);if editing != nil {h.dues.removeAll{d in d.ruleId==r.id && d.date>Dates.today() && !h.transactions.contains{$0.dueId==d.id}}}}){dismiss()}}}catch{error=error.localizedDescription}}
}
struct CategoryEditor:View {
    @EnvironmentObject var store:Store;@Environment(\.dismiss) var dismiss;let h:Household;let editing:Category?
    @State var name:String;@State var income:Bool;@State var icon="cart";@State var tint="green"
    init(h:Household,editing:Category?=nil){self.h=h;self.editing=editing;_name=State(initialValue:editing?.name ?? "");_income=State(initialValue:editing?.income ?? false);if let editing{_icon=State(initialValue:UserDefaults.standard.string(forKey:"icon-"+editing.id) ?? "cart");_tint=State(initialValue:UserDefaults.standard.string(forKey:"tint-"+editing.id) ?? "green")}}
    var body:some View{EditorFrame(title:"التصنيف",save:{let c=Category(id:editing?.id ?? uid(),name:name.trimmingCharacters(in:.whitespaces),income:income,archived:editing?.archived ?? false);Task{if await store.change(transform:{h in h.categories.removeAll{$0.id==c.id};h.categories.append(c)}){UserDefaults.standard.set(icon,forKey:"icon-"+c.id);UserDefaults.standard.set(tint,forKey:"tint-"+c.id);dismiss()}}}){FormField(label:"اسم التصنيف",text:$name);Toggle("تصنيف دخل",isOn:$income).disabled(editing != nil);Picker("الأيقونة",selection:$icon){ForEach(["cart","heart","book","car","star","house","creditcard","wallet.pass","gift","tshirt"],id:\.self){Label($0,systemImage:$0).tag($0)}};Picker("اللون",selection:$tint){Text("أخضر").tag("green");Text("برتقالي").tag("orange");Text("أزرق").tag("blue")}}}
}
struct PlanEditor:View {
    @EnvironmentObject var store:Store;@Environment(\.dismiss) var dismiss;let h:Household;let period:Cycle
    @State var income:String;@State var variable:String;@State var commitments:String;@State var saving:String;@State var reserve:String;@State var date:String;@State var note:String;@State var error:String?
    init(h:Household,period:Cycle){self.h=h;self.period=period;let p=h.plans.first{$0.period==period.start};_income=State(initialValue:Finance.input(p?.income ?? 0));_variable=State(initialValue:Finance.input(p?.variable ?? 0));_commitments=State(initialValue:Finance.input(p?.commitments ?? h.dues.reduce(0){$0+(period.contains($1.date) ? $1.amount:$1.date<period.start ? h.remaining($1):0)}));_saving=State(initialValue:Finance.input(p?.saving ?? 0));_reserve=State(initialValue:Finance.input(p?.reserve ?? 0));_date=State(initialValue:p?.incomeDate ?? period.start);_note=State(initialValue:p?.note ?? "")}
    var body:some View{EditorFrame(title:"خطة الشهر",save:save){Hint(period.start);FormField(label:"الدخل المتوقع",text:$income,number:true,identifier:"plan-income");FormField(label:"الصرف المتغير",text:$variable,number:true);FormField(label:"الالتزامات",text:$commitments,number:true);FormField(label:"الادخار",text:$saving,number:true);FormField(label:"الاحتياطي",text:$reserve,number:true);FormField(label:"موعد الدخل YYYY-MM-DD",text:$date);FormField(label:"ملاحظات",text:$note);Hint("الخطة لا تنشئ دخلًا أو مصروفًا تلقائيًا");if let error{Text(error).foregroundStyle(.red)}}}
    func save(){do{let p=MonthlyPlan(period:period.start,income:try Finance.money(income),variable:try Finance.money(variable),commitments:try Finance.money(commitments),saving:try Finance.money(saving),reserve:try Finance.money(reserve),incomeDate:date,note:String(note.prefix(500)));Task{if await store.change(transform:{h in h.plans.removeAll{$0.period==p.period};h.plans.append(p);h.schema=2}){dismiss()}}}catch{error=error.localizedDescription}}
}
struct TemplateEditor:View {
    @EnvironmentObject var store:Store;@Environment(\.dismiss) var dismiss;let h:Household;let editing:QuickTemplate?
    @State var title:String;@State var type:TxType;@State var amount:String;@State var account:String;@State var category:String;@State var note:String;@State var error:String?
    init(h:Household,editing:QuickTemplate?=nil){self.h=h;self.editing=editing;_title=State(initialValue:editing?.title ?? "");_type=State(initialValue:editing?.type ?? .expense);_amount=State(initialValue:editing.map{Finance.input($0.amount)} ?? "");_account=State(initialValue:editing?.accountId ?? h.prefs.defaultAccount ?? h.accounts.first?.id ?? "");_category=State(initialValue:editing?.categoryId ?? "expense-0");_note=State(initialValue:editing?.note ?? "")}
    var body:some View{EditorFrame(title:"قالب سريع",save:save){FormField(label:"اسم القالب",text:$title);Picker("النوع",selection:$type){Text("مصروف").tag(TxType.expense);Text("دخل").tag(TxType.income)}.pickerStyle(.segmented);FormField(label:"المبلغ",text:$amount,number:true);Picker("الحساب",selection:$account){ForEach(h.accounts.filter{!$0.archived}){Text($0.name).tag($0.id)}};Picker("التصنيف",selection:$category){ForEach(h.categories.filter{!$0.archived && $0.income==(type == .income)}){Text($0.name).tag($0.id)}};FormField(label:"الملاحظة",text:$note);Hint("يفتح القالب مسودة بتاريخ اليوم؛ لا حفظ تلقائي");if let error{Text(error).foregroundStyle(.red)}}.onChange(of:type){_,t in category=h.categories.first{!$0.archived && $0.income==(t == .income)}?.id ?? ""}}
    func save(){do{let t=QuickTemplate(id:editing?.id ?? uid(),title:title,type:type,amount:try Finance.money(amount),accountId:account,categoryId:category,note:note);Task{if await store.change(transform:{h in h.templates.removeAll{$0.id==t.id};h.templates.append(t)}){dismiss()}}}catch{error=error.localizedDescription}}
}
struct GoalEditor:View {
    @EnvironmentObject var store:Store;@Environment(\.dismiss) var dismiss;let h:Household
    @State var title:String;@State var target:String;@State var account:String;@State var error:String?
    init(h:Household){self.h=h;_title=State(initialValue:h.prefs.goal.title);_target=State(initialValue:Finance.input(h.prefs.goal.target));_account=State(initialValue:h.prefs.goal.accountId ?? "")}
    var body:some View{EditorFrame(title:"هدف الادخار",save:{do{let value=try Finance.money(target);Task{if await store.change(transform:{h in h.prefs.goal=SavingGoal(title:title,target:value,accountId:account.isEmpty ? nil:account)}){dismiss()}}}catch{error=error.localizedDescription}}){FormField(label:"الهدف",text:$title);FormField(label:"المبلغ المستهدف",text:$target,number:true);Picker("حساب الادخار",selection:$account){Text("كل الحسابات").tag("");ForEach(h.accounts){Text($0.name).tag($0.id)}};Hint("التقدم يقيس رصيد الحساب المختار؛ الهدف لا يخصم الأموال تلقائيًا");if let error{Text(error).foregroundStyle(.red)}}}
}
