import SwiftUI
import Charts

struct HomeView:View {
    @EnvironmentObject var store:Store
    let period:Cycle; let open:(EditorRoute)->Void
    var body:some View { if let h=store.data { let report=Analytics(data:h,period:period); let budget=h.budget(period)?.amount ?? 0; let available=budget-report.expense-report.outstanding
        Page {
            Text("كل شيء أوضح").font(.title.bold()); Hint(period.start+" إلى "+Dates.add(period.end,days:-1))
            MewCard(prominent:true) { VStack(alignment:.leading,spacing:14) { MoneyView(label:h.budget(period)==nil ? "الفائض المسجل":"المتاح بعد الالتزامات",amount:h.budget(period)==nil ? report.surplus:available,main:true).accessibilityIdentifier("home-amount"); Hint(h.budget(period)==nil ? "حدد ميزانية لتعرف المتاح للصرف. الفائض يختلف عن أرصدة الحسابات.":"الميزانية − صافي المصروف − الالتزامات غير المدفوعة"); HStack{Cat(size:48);Hint("محجوز للالتزامات "+Finance.format(report.outstanding))} } }
            ViewThatFits(in:.horizontal) { HStack { metric("صافي المصروفات",report.expense,true);metric("الدخل الفعلي",report.income,false) }; VStack{metric("صافي المصروفات",report.expense,true);metric("الدخل الفعلي",report.income,false)} }
            if let b=h.budget(period){MewCard { VStack(alignment:.leading,spacing:10){ Text("ميزانية البيت").font(.headline); MoneyView(label:"المتبقي",amount:b.amount-report.expense); ProgressView(value:b.amount>0 ? min(1,max(0,Double(report.expense)/Double(b.amount))):0); Hint("المحدد "+Finance.format(b.amount)) } }}
            MewCard { VStack(alignment:.leading,spacing:12){Text("الإجراء التالي").font(.headline); if let due=h.dues.filter({$0.date<period.end && h.remaining($0)>0}).first{Text(due.title+" • "+due.date);Button("تسجيل سداد"){open(EditorRoute(kind:"due",due:due))}}else{Text("لا توجد التزامات قريبة غير مدفوعة");Hint("سجل المصروف أولًا بأول لتكون الصورة أوضح")}; if let daily=report.availableDaily{MoneyView(label:"متاح يوميًا لبقية الدورة",amount:daily)};if let forecast=report.forecast{MoneyView(label:"توقع نهاية الدورة",amount:forecast);Hint("تقدير مبني على سجل 7 أيام على الأقل؛ ليس وعدًا أو ميزانية معتمدة")} } }
            if !h.templates.isEmpty { MewCard { VStack(alignment:.leading){Text("قوالبك السريعة").font(.headline);ForEach(h.templates.prefix(3)){t in Button(t.title+" • "+Finance.format(t.amount)){open(EditorRoute(kind:t.type == .income ? "income":"expense",template:t))}.disabled(!h.templateAvailable(t)).padding(.vertical,6)} } } }
            Text("آخر العمليات").font(.headline);ForEach(h.transactions.sorted{($0.date,$0.created)>($1.date,$1.created)}.prefix(3)){t in Button{open(EditorRoute(kind:"transaction",transaction:t))}label:{MewCard{TxRow(h:h,t:t)}}.buttonStyle(.plain)}
            if h.transactions.isEmpty{EmptyState(title:"ابدأ بأول عملية",detail:"اضغط إضافة مصروف؛ الأرصدة الافتتاحية لا تدخل ضمن الدخل")}
        }
    } }
    func metric(_ label:String,_ value:Int64,_ warm:Bool)->some View { MoneyView(label:label,amount:value).padding(16).frame(maxWidth:.infinity,alignment:.leading).background(warm ? Brand.orange.opacity(0.17):Color.primary.opacity(0.045),in:RoundedRectangle(cornerRadius:18)) }
}
struct TransactionsView:View {
    @EnvironmentObject var store:Store
    let period:Cycle; let open:(EditorRoute)->Void
    @State var query=""; @State var type=""; @State var account=""; @State var category=""; @State var all=false; @State var dateFrom=""; @State var dateTo=""; @State var minAmount=""; @State var maxAmount=""; @State var filters=false
    var body:some View { if let h=store.data { Page { Text("سجل العمليات").font(.title.bold());TextField("ابحث بالملاحظة أو التصنيف أو الحساب",text:$query).textFieldStyle(.roundedBorder).accessibilityIdentifier("transactions-search");Toggle("كل الفترات",isOn:$all);DisclosureGroup("الفلاتر",isExpanded:$filters){Picker("النوع",selection:$type){Text("الكل").tag("");ForEach(TxType.allCases){Text($0.title).tag($0.rawValue)}};Picker("الحساب",selection:$account){Text("الكل").tag("");ForEach(h.accounts){Text($0.name).tag($0.id)}};Picker("التصنيف",selection:$category){Text("الكل").tag("");ForEach(h.categories){Text($0.name).tag($0.id)}};FormField(label:"من YYYY-MM-DD",text:$dateFrom);FormField(label:"إلى YYYY-MM-DD",text:$dateTo);FormField(label:"الحد الأدنى — جنيه",text:$minAmount,number:true);FormField(label:"الحد الأقصى — جنيه",text:$maxAmount,number:true)}
        let rows=filtered(h);Hint("\(rows.count) عملية • صافي مصروفات "+Finance.format(rows.reduce(0){$0+($1.type == .expense ? $1.amount:$1.type == .refund ? -$1.amount:0)})); if rows.isEmpty{EmptyState(title:"لا توجد عمليات مطابقة",detail:"غيّر الفترة أو أزل الفلاتر");Button("إعادة ضبط الفلاتر"){query="";type="";account="";category="";dateFrom="";dateTo="";minAmount="";maxAmount="";all=false}}
        ForEach(rows){t in MewCard{VStack(alignment:.leading){TxRow(h:h,t:t);HStack{Button("تعديل"){open(EditorRoute(kind:"transaction",transaction:t))}.accessibilityIdentifier("edit-"+t.id);if t.type == .expense{Button("استرداد"){open(EditorRoute(kind:"refund",transaction:t))};Button("حذف",role:.destructive){Task{await store.delete(t)}}}.buttonStyle(.bordered)}} }
    } } }
    func filtered(_ h:Household)->[Transaction] { let ids=Set(Search.hits(h,query:query).filter{$0.kind=="transaction"}.map(\.id));let lo=try? Finance.money(minAmount);let hi=try? Finance.money(maxAmount);return h.transactions.filter{ t in (all || period.contains(t.date)) && (query.isEmpty || ids.contains(t.id)) && (type.isEmpty || t.type.rawValue==type) && (account.isEmpty || t.accountId==account || t.destinationId==account) && (category.isEmpty || t.categoryId==category) && (dateFrom.isEmpty || t.date>=dateFrom) && (dateTo.isEmpty || t.date<=dateTo) && (lo==nil || t.amount>=lo!) && (hi==nil || t.amount<=hi!) }.sorted{($0.date,$0.created)>($1.date,$1.created)} }
}
struct AnalyticsView:View {
    @EnvironmentObject var store:Store
    var period:Cycle;var open:(EditorRoute)->Void
    @State var tab="overview";@State var category="expense-0";@State var reduction=10;@State var unit="day";@State var evidence:[Transaction]=[];@State var evidenceTitle="";@State var showEvidence=false
    var body:some View { if let h=store.data { let a=Analytics(data:h,period:period)
        Page {
            Text("تحليلات واضحة").font(.title.bold());Hint("تحليل السجلات المدخلة فقط؛ لا يفترض اكتمال التسجيل")
            ScrollView(.horizontal){HStack{ForEach([("overview","نظرة عامة"),("details","تفاصيل الإنفاق"),("comparison","المقارنات"),("saving","خطة التوفير")],id:\.0){id,title in Button(title){tab=id}.buttonStyle(.bordered).tint(tab==id ? Brand.orange:Brand.green).accessibilityIdentifier("analysis-"+id)}}}.scrollIndicators(.hidden)
            switch tab {
            case "details": details(a,h)
            case "comparison": comparison(a,h)
            case "saving": saving(a,h)
            default:
                MewCard(prominent:true){VStack(alignment:.leading,spacing:14){MoneyView(label:"صافي المصروفات",amount:a.expense,main:true);MoneyView(label:"الدخل المسجل",amount:a.income);MoneyView(label:"الفائض المسجل",amount:a.surplus);Hint("التحويلات والأرصدة الافتتاحية ليست دخلًا ولا مصروفًا")}}
                if let forecast=a.forecast{MewCard{MoneyView(label:"توقع نهاية الدورة",amount:forecast)}}
                Text("القطة تلخص لك").font(.headline);if a.signals.isEmpty{Hint("لا توجد إشارات تستحق المراجعة في السجل الحالي")};ForEach(a.signals){s in Button{evidence=s.rows;evidenceTitle=s.title;showEvidence=true}label:{MewCard{VStack(alignment:.leading,spacing:8){Text(s.title).font(.headline);Hint(s.detail)}}}.buttonStyle(.plain)}
                if let b=h.budget(period),a.expense>b.amount{MewCard{Text("تجاوز ميزانية البيت بـ "+Finance.format(a.expense-b.amount)).foregroundStyle(.red)}}
            }
        }.sheet(isPresented:$showEvidence){NavigationStack{Page{Text(evidenceTitle).font(.title2.bold());ForEach(evidence){t in Button{showEvidence=false;open(EditorRoute(kind:"transaction",transaction:t))}label:{MewCard{TxRow(h:h,t:t)}}.buttonStyle(.plain)}}.toolbar{ToolbarItem(placement:.cancellationAction){Button("إغلاق"){showEvidence=false}}}}}
    } }
    func details(_ a:Analytics,_ h:Household)->some View { Group { MewCard{ VStack(alignment:.leading,spacing:12){Text("توزيع المصروفات").font(.headline); Chart(a.stats.filter{$0.net>0}){c in BarMark(x:.value("المبلغ",Double(c.net)/100),y:.value("التصنيف",h.category(c.id))).foregroundStyle(Brand.orange)}.frame(height:max(160,CGFloat(a.stats.count*32)));Hint("الاستردادات تقلل الصافي؛ القيم السالبة تظهر في التفاصيل")} };ForEach(a.stats){c in Button{evidence=c.rows;evidenceTitle=h.category(c.id);showEvidence=true}label:{MewCard{VStack(alignment:.leading,spacing:8){MoneyView(label:h.category(c.id),amount:c.net);Hint("\(c.count) عمليات • متوسط المدفوع "+Finance.format(c.average));Hint("مدفوعات "+Finance.format(c.gross)+" • استردادات "+Finance.format(c.refunds))}}}.buttonStyle(.plain)};MewCard{VStack(alignment:.leading){Picker("التجميع",selection:$unit){Text("يومي").tag("day");Text("أسبوعي").tag("week");Text("شهري").tag("month")}.pickerStyle(.segmented);let buckets=a.buckets(unit); Chart(Array(buckets.enumerated()),id:\.offset){v in BarMark(x:.value("الفترة",v.element.0),y:.value("جنيه",Double(v.element.1)/100)).foregroundStyle(Brand.green)}.frame(height:200); ForEach(buckets,id:\.0){key,value in Button{evidence=a.rows.filter{t in let p=Analytics(data:h,period:Cycle(start:t.date,end:Dates.add(t.date,days:1)));return p.buckets(unit).contains{$0.0==key} && [.expense,.refund].contains(t.type)};evidenceTitle=key;showEvidence=true}label:{HStack{Text(key);Spacer();Text(Finance.format(value))}}} }} } }
    func comparison(_ a:Analytics,_ h:Household)->some View { Group { MewCard{VStack(alignment:.leading,spacing:10){Text("مقارنة مدد متساوية").font(.headline);if !a.comparable{Hint("لا توجد تغطية متساوية منذ بدء المتابعة؛ لا مقارنة مضللة")}else{ForEach(a.windows.indices,id:\.self){i in MoneyView(label:i==0 ? "الدورة الحالية":"الدورة السابقة",amount:Finance.expense(h.transactions,a.windows[i]));Hint(a.windows[i].start+" • \(a.windows[i].days) يوم")};let current=Finance.categories(h.transactions,a.windows[0]);let previous=Finance.categories(h.transactions,a.windows[1]);ForEach(Array(Set(current.keys).union(previous.keys)).sorted(),id:\.self){id in Button{evidence=h.transactions.filter{tx in [a.windows[0],a.windows[1]].contains{p in p.contains(tx.date)} && tx.categoryId==id};evidenceTitle=h.category(id);showEvidence=true}label:{MoneyView(label:"تغير "+h.category(id),amount:current[id,default:0]-previous[id,default:0])}}}}};MewCard{VStack(alignment:.leading,spacing:10){Text("آخر الدورات").font(.headline);ForEach(a.history(),id:\.0.start){p,income,expense in Text(p.start);Hint("دخل "+Finance.format(income)+" • صافي مصروف "+Finance.format(expense))}}} } }
    func saving(_ a:Analytics,_ h:Household)->some View { let next=Analytics.nextPlan(h); let simulation=a.simulate(category,reduction:reduction);return Group { MewCard{VStack(alignment:.leading,spacing:12){Text("محاكاة توفير").font(.headline);Picker("التصنيف",selection:$category){ForEach(h.categories.filter{!$0.income}){Text($0.name).tag($0.id)}};Stepper("خفض \(reduction)%",value:$reduction,in:0...50,step:5);MoneyView(label:"التوفير المحتمل",amount:simulation.saving);MoneyView(label:"المصروف بعد المحاكاة",amount:simulation.expense);MoneyView(label:"الفائض بعد المحاكاة",amount:simulation.surplus);Hint("المحاكاة لا تعدّل العمليات أو الميزانية")}};MewCard{VStack(alignment:.leading,spacing:12){Text("اقتراح الدورة التالية").font(.headline);Hint(next.period.start);if let variable=next.variable{MoneyView(label:"متوسط الإنفاق المتغير",amount:variable);Hint("من \(next.history) دورات سابقة بها مصروفات؛ اكتمال السجل مسؤولية المستخدم");MoneyView(label:"التزامات ومتأخرات",amount:next.commitments+next.carryover);Button("اعتماد ميزانية الدورة التالية"){Task{_ = await store.change("تم اعتماد الميزانية بعد اختيارك"){h in h.budgets.removeAll{$0.period==next.period.start && $0.categoryId==nil};h.budgets.append(Budget(period:next.period.start,amount:variable+next.commitments+next.carryover))}}}.accessibilityIdentifier("adopt-budget")}else{Hint("لا توجد دورة سابقة مكتملة زمنيًا وبها مصروفات؛ حدد الميزانية بنفسك")}}} } }
}
struct PlanView:View {
    @EnvironmentObject var store:Store;var period:Cycle;var open:(EditorRoute)->Void
    @State var calendar=false;@State var month=String(Dates.today().prefix(7));@State var selected=Dates.today()
    var body:some View { if let h=store.data { Page { Text(calendar ? "التقويم المالي":"خطة الشهر").font(.title.bold());Picker("العرض",selection:$calendar){Text("خطة الشهر").tag(false);Text("المواعيد").tag(true)}.pickerStyle(.segmented)
        if calendar { MewCard{VStack(alignment:.leading,spacing:12){HStack{Button("السابق"){month=String(Dates.add(month+"-01",months:-1).prefix(7))};Spacer();Text(month);Spacer();Button("التالي"){month=String(Dates.add(month+"-01",months:1).prefix(7))}};let first=month+"-01";let count=Dates.days(first,Dates.add(first,months:1));ScrollView(.horizontal){LazyVGrid(columns:Array(repeating:GridItem(.fixed(44),spacing:4),count:7),spacing:4){ForEach(1...max(1,count),id:\.self){day in let date=String(format:"%@-%02d",month,day);Button{selected=date}label:{Text("\(day)").frame(width:44,height:44).background(date==selected ? Brand.orange.opacity(0.3):Color.primary.opacity(0.04),in:RoundedRectangle(cornerRadius:10))}.accessibilityLabel(date)}}};Hint("اضغط اليوم لعرض المواعيد؛ تمرير أفقي على الشاشات الصغيرة")}}
            ForEach(h.dues.filter{$0.date==selected}){d in MewCard{VStack(alignment:.leading,spacing:10){Text(d.title).font(.headline);MoneyView(label:h.remaining(d)==0 ? "مدفوع":"متبقي",amount:h.remaining(d));if h.remaining(d)>0{Button("سداد"){open(EditorRoute(kind:"due",due:d))}}}};ForEach(h.plans.filter{$0.incomeDate==selected}){p in MewCard{MoneyView(label:"دخل مخطط فقط",amount:p.income)}}
        } else { if let p=h.plans.first(where:{$0.period==period.start}) {MewCard(prominent:true){VStack(alignment:.leading,spacing:12){MoneyView(label:"الدخل المخطط",amount:p.income,main:true);MoneyView(label:"صرف متغير",amount:p.variable);MoneyView(label:"التزامات",amount:p.commitments);MoneyView(label:"ادخار",amount:p.saving);MoneyView(label:"احتياطي",amount:p.reserve);Hint("دخل متوقع في "+p.incomeDate);if p.allocated>p.income{Text("التوزيع يتجاوز الدخل المخطط").foregroundStyle(.red)}else{Hint("غير موزع "+Finance.format(p.income-p.allocated))};Hint(p.note)}};let actual=Analytics(data:h,period:period);MewCard{VStack(alignment:.leading,spacing:12){MoneyView(label:"الدخل الفعلي",amount:actual.income);MoneyView(label:"الصرف الفعلي",amount:actual.expense);MoneyView(label:"التزامات مسددة",amount:Finance.expense(h.transactions.filter{$0.dueId != nil},period));Hint("الخطة لا تُنشئ دخلًا أو عمليات تلقائيًا")}};Button("اعتماد مبلغ الصرف كميزانية"){Task{_ = await store.change{h in h.budgets.removeAll{$0.period==period.start && $0.categoryId==nil};h.budgets.append(Budget(period:period.start,amount:p.spending))}}} }else{EmptyState(title:"خطط لدورتك",detail:"وزع الدخل المتوقع بين الصرف والالتزامات والادخار والاحتياطي")};Button("تحرير خطة الشهر"){open(EditorRoute(kind:"plan"))}.buttonStyle(.borderedProminent).accessibilityIdentifier("edit-plan") }
    } } }
}
