import SwiftUI
import UniformTypeIdentifiers
struct MoreView:View {
    var period:Cycle;var open:(EditorRoute)->Void
    var body:some View {Page{Text("أدوات بيتك").font(.title.bold());NavigationLink{AccountsView(open:open)}label:{link("الحسابات وهدف الادخار","wallet.pass")};NavigationLink{BudgetView(period:period)}label:{link("ميزانية الدورة","chart.pie")};NavigationLink{DuesView(open:open)}label:{link("الفواتير والأقساط","calendar.badge.clock")};NavigationLink{TemplatesView(open:open)}label:{link("القوالب السريعة","square.grid.2x2")};NavigationLink{CategoriesView(open:open)}label:{link("التصنيفات","tag")};NavigationLink{SettingsView(period:period,open:open)}label:{link("الإعدادات والخصوصية","gearshape")}.accessibilityIdentifier("more-settings");NavigationLink{BackupView(period:period)}label:{link("النسخ الاحتياطي والتقارير","square.and.arrow.up")}.accessibilityIdentifier("more-backup")}.buttonStyle(.plain)}
    func link(_ text:String,_ icon:String)->some View {MewCard{Label(text,systemImage:icon).font(.headline).frame(maxWidth:.infinity,minHeight:44,alignment:.leading)}}
}
struct BudgetView:View {
    @EnvironmentObject var store:Store;var period:Cycle
    @State var category="";@State var amount="";@State var error:String?
    var body:some View {if let h=store.data{let spent=Finance.expense(h.transactions,period);Page{Text("ميزانية الدورة").font(.title.bold());if let b=h.budget(period){MewCard(prominent:true){VStack(alignment:.leading,spacing:10){MoneyView(label:"المتبقي من ميزانية البيت",amount:b.amount-spent,main:true);ProgressView(value:b.amount>0 ? min(1,max(0,Double(spent)/Double(b.amount))):0);Hint("المحدد "+Finance.format(b.amount)+" • المصروف "+Finance.format(spent))}}};MewCard{VStack(alignment:.leading,spacing:12){Picker("الميزانية",selection:$category){Text("البيت بالكامل").tag("");ForEach(h.categories.filter{!$0.income && !$0.archived}){Text($0.name).tag($0.id)}};FormField(label:"المبلغ المحدد — جنيه",text:$amount,number:true,identifier:"budget-amount");Hint("ميزانيات البنود جزء من ميزانية البيت؛ لا تُجمع معه لحساب الإنفاق");if let error{Text(error).foregroundStyle(.red)};Button("حفظ الميزانية"){do{let b=Budget(period:period.start,amount:try Finance.money(amount),categoryId:category.isEmpty ? nil:category);Task{_ = await store.change{h in h.budgets.removeAll{$0.id==b.id};h.budgets.append(b)}}}catch{self.error=error.localizedDescription}}.buttonStyle(.borderedProminent).accessibilityIdentifier("budget-save")}}
        let budgets=h.budgets.filter{$0.period==period.start};let distribution=Finance.categories(h.transactions,period);let allocated=budgets.filter{$0.categoryId != nil}.reduce(0){$0+$1.amount};if let total=h.budget(period){Hint(allocated>total.amount ? "مجموع ميزانيات البنود يتجاوز ميزانية البيت":"ميزانية غير موزعة "+Finance.format(total.amount-allocated))};ForEach(budgets){b in MewCard{VStack(alignment:.leading,spacing:10){let value=b.categoryId==nil ? spent:distribution[b.categoryId!,default:0];MoneyView(label:b.categoryId==nil ? "البيت بالكامل":h.category(b.categoryId),amount:b.amount-value);Hint("المحدد "+Finance.format(b.amount)+" • المصروف "+Finance.format(value));if value>b.amount{Text("تجاوز "+Finance.format(value-b.amount)).foregroundStyle(.red)};Button("إزالة الميزانية",role:.destructive){Task{_ = await store.change{h in h.budgets.removeAll{$0.id==b.id}}}}}};if !budgets.isEmpty{Button("نسخ الميزانيات الناقصة للدورة التالية"){Task{_ = await store.change{h in let next=h.cycle(period.end);for b in budgets where h.budget(next,category:b.categoryId)==nil{h.budgets.append(Budget(period:next.start,amount:b.amount,categoryId:b.categoryId))}}}}}else{EmptyState(title:"لا توجد ميزانية",detail:"حدد مبلغًا للبيت أو لأحد البنود")}
    }.onAppear{fill(h)}.onChange(of:category){_,_ in fill(store.data ?? h)}}}
    func fill(_ h:Household){amount=h.budget(period,category:category.isEmpty ? nil:category).map{Finance.input($0.amount)} ?? ""}
}
struct AccountsView:View {
    @EnvironmentObject var store:Store;var open:(EditorRoute)->Void
    var body:some View{if let h=store.data{Page{Text("حساباتي ومحافظي").font(.title.bold());MoneyView(label:"إجمالي الأرصدة الحالية",amount:h.accounts.reduce(0){$0+h.balance($1)},main:true);Button("إضافة حساب أو محفظة"){open(EditorRoute(kind:"account"))}.buttonStyle(.borderedProminent);ForEach(h.accounts){a in MewCard{VStack(alignment:.leading,spacing:12){Text(a.name).font(.headline);Hint(a.kind+(a.archived ? " • مؤرشف":""));MoneyView(label:"الرصيد الحالي",amount:h.balance(a));Hint("افتتاحي "+Finance.format(a.opening));ViewThatFits{HStack{controls(a,h)};VStack(alignment:.leading){controls(a,h)}}}}};MewCard{VStack(alignment:.leading,spacing:12){Text("هدف الادخار").font(.headline);if h.prefs.goal.target>0{MoneyView(label:h.prefs.goal.title,amount:h.prefs.goal.target);let account=h.accounts.first{$0.id==h.prefs.goal.accountId};let balance=account.map{h.balance($0)} ?? h.accounts.reduce(0){$0+h.balance($1)};MoneyView(label:"الرصيد المخصص",amount:balance);ProgressView(value:min(1,max(0,Double(balance)/Double(h.prefs.goal.target))))};Button("تحديد أو تعديل الهدف"){open(EditorRoute(kind:"goal"))};Hint("اختر حساب ادخار مخصصًا؛ التحويل إليه ليس مصروفًا")}};Hint("قد يظهر رصيد سالب إذا سجلت صرفًا أكبر من الرصيد؛ راجع السجلات دون إنشاء دخل وهمي")}}}
    @ViewBuilder func controls(_ a:Account,_ h:Household)->some View{Button("تعديل"){open(EditorRoute(kind:"account",account:a))};if !a.archived{Button(h.prefs.defaultAccount==a.id ? "افتراضي ✓":"اجعله افتراضيًا"){Task{_ = await store.change{$0.prefs.defaultAccount=a.id}}}};Button(a.archived ? "إلغاء الأرشفة":"أرشفة"){Task{_ = await store.change{h in let others=h.accounts.filter{!$0.archived && $0.id != a.id};try require(a.archived || !others.isEmpty,"احتفظ بحساب نشط واحد على الأقل");h.accounts=h.accounts.map{var v=$0;if v.id==a.id{v.archived.toggle()};return v};if !a.archived && h.prefs.defaultAccount==a.id{h.prefs.defaultAccount=others.first?.id}}}}}
}
struct DuesView:View {
    @EnvironmentObject var store:Store;var open:(EditorRoute)->Void
    @State var showPaid=false;@State var editing:Due?;@State var amount="";@State var error:String?
    var body:some View{if let h=store.data{Page{Text("الفواتير والأقساط").font(.title.bold());Button("التزام متكرر جديد"){open(EditorRoute(kind:"rule"))}.buttonStyle(.borderedProminent);Hint("المتأخرات والاستحقاقات خلال 60 يومًا. لا تدخل المبالغ المخططة المصروف قبل السداد.");Toggle("إظهار المدفوع أيضًا",isOn:$showPaid);let dues=h.dues.filter{(showPaid || h.remaining($0)>0) && $0.date<=Dates.add(Dates.today(),days:60)};if dues.isEmpty{EmptyState(title:"لا توجد استحقاقات مطابقة",detail:"أضف فاتورة أو قسطًا للتذكير وتنظيم السداد")};ForEach(dues){d in MewCard{VStack(alignment:.leading,spacing:12){Text(d.title).font(.headline);Hint(d.date+" • "+h.category(d.categoryId)+" • "+(h.remaining(d)==0 ? "مدفوع":d.date<Dates.today() ? "متأخر":h.paid(d)>0 ? "مدفوع جزئيًا":"مستحق"));MoneyView(label:"المتبقي",amount:h.remaining(d));Hint("مخطط "+Finance.format(d.amount)+" • مدفوع "+Finance.format(h.paid(d)));if h.remaining(d)>0{Button("تسجيل سداد"){open(EditorRoute(kind:"due",due:d))}};Button("تعديل مبلغ هذا الاستحقاق"){amount=Finance.input(d.amount);editing=d}}}};Text("إدارة التكرار").font(.headline);ForEach(h.rules){r in MewCard{VStack(alignment:.leading,spacing:10){Text(r.title).font(.headline);Hint(r.active ? "نشط":"متوقف");Button("تعديل"){open(EditorRoute(kind:"rule",rule:r))};Button(r.active ? "إيقاف":"تفعيل"){Task{_ = await store.change{h in h.rules=h.rules.map{var v=$0;if v.id==r.id{v.active.toggle()};return v};if r.active{h.dues.removeAll{d in d.ruleId==r.id && d.date>Dates.today() && !h.transactions.contains{$0.dueId==d.id}}}}}}}};Hint("إيقاف التكرار يزيل المواعيد المستقبلية غير المرتبطة بالسداد؛ السجل السابق يبقى")}.sheet(item:$editing){d in EditorFrame(title:"المبلغ المخطط",save:{do{let value=try Finance.money(amount);try require(value>0 && value>=(store.data ?? h).paid(d),"المبلغ أكبر من صفر ولا يقل عن المدفوع");Task{if await store.change(transform:{h in h.dues=h.dues.map{var v=$0;if v.id==d.id{v.amount=value};return v}}){editing=nil}}}catch{self.error=error.localizedDescription}}){Hint(d.title+" • "+d.date);FormField(label:"المبلغ — جنيه",text:$amount,number:true);Hint("لهذا الموعد فقط؛ لا يغيّر القاعدة المستقبلية أو المصروف الفعلي");if let error{Text(error).foregroundStyle(.red)}}}}}
}
struct TemplatesView:View {
    @EnvironmentObject var store:Store;var open:(EditorRoute)->Void
    var body:some View{if let h=store.data{Page{Text("القوالب السريعة").font(.title.bold());Button("قالب جديد"){open(EditorRoute(kind:"template"))}.buttonStyle(.borderedProminent);if h.templates.isEmpty{EmptyState(title:"وفّر خطوات الإدخال",detail:"احفظ مصروفًا أو دخلًا متكررًا كقالب؛ كل استخدام يفتح مسودة للمراجعة")};ForEach(h.templates){t in MewCard{VStack(alignment:.leading,spacing:12){Text(t.title).font(.headline);MoneyView(label:t.type.title,amount:t.amount);Hint(h.account(t.accountId)+" • "+h.category(t.categoryId));Button("استخدام القالب"){open(EditorRoute(kind:t.type == .income ? "income":"expense",template:t))}.disabled(!h.templateAvailable(t));Button("تعديل"){open(EditorRoute(kind:"template",template:t))};Button("حذف",role:.destructive){Task{_ = await store.change{h in h.templates.removeAll{$0.id==t.id}}}}}}}}}
}
struct CategoriesView:View {
    @EnvironmentObject var store:Store;var open:(EditorRoute)->Void
    var body:some View{if let h=store.data{Page{Text("التصنيفات").font(.title.bold());Button("إضافة تصنيف"){open(EditorRoute(kind:"category"))}.buttonStyle(.borderedProminent);ForEach(h.categories){c in MewCard{VStack(alignment:.leading,spacing:12){Label(c.name,systemImage:UserDefaults.standard.string(forKey:"icon-"+c.id) ?? (c.income ? "wallet.pass":"cart")).foregroundStyle(UserDefaults.standard.string(forKey:"tint-"+c.id)=="orange" ? Brand.orange:UserDefaults.standard.string(forKey:"tint-"+c.id)=="blue" ? Color.blue:Brand.green);Hint((c.income ? "دخل":"مصروف")+(c.archived ? " • مؤرشف":""));Button("تعديل الاسم والأيقونة"){open(EditorRoute(kind:"category",category:c))};Button(c.archived ? "إلغاء الأرشفة":"أرشفة"){Task{_ = await store.change{h in h.categories=h.categories.map{var v=$0;if v.id==c.id{v.archived.toggle()};return v}}}}}}}}}
}
struct SettingsView:View {
    @EnvironmentObject var store:Store;var period:Cycle;var open:(EditorRoute)->Void
    @AppStorage("theme") var theme="system";@AppStorage("glass") var glass=true;@AppStorage("reduce-effects") var reduce=false
    @State var salary=25
    var body:some View{if let h=store.data{Page{Text("الإعدادات والخصوصية").font(.title.bold());MewCard{VStack(alignment:.leading,spacing:12){Text("مظهر التطبيق").font(.headline);ForEach([("system","حسب الهاتف"),("light","فاتح"),("dark","داكن")],id:\.0){id,title in Button{theme=id}label:{HStack{Text(title);Spacer();if theme==id{Image(systemName:"checkmark")}}.frame(minHeight:44)}.accessibilityIdentifier("theme-"+id)};Toggle("المظهر الزجاجي",isOn:$glass);Toggle("تقليل التأثيرات",isOn:$reduce);Hint("يحترم التطبيق أيضًا تقليل الحركة والشفافية في إعدادات iPhone")}};MewCard{VStack(alignment:.leading,spacing:12){Text("بيتك").font(.headline);Hint("بداية المتابعة: "+h.prefs.trackingStart);Stepper("بداية الدورة: يوم \(salary)",value:$salary,in:1...31);Button("حفظ يوم بداية الدورة"){Task{_ = await store.change{$0.prefs.salaryDay=salary}}};Hint("العمليات وتواريخها لا تتغير؛ الميزانيات السابقة تبقى مربوطة ببداياتها القديمة")}};MewCard{VStack(alignment:.leading,spacing:12){Text("الخصوصية والقفل").font(.headline);Toggle("Face ID أو قفل الهاتف",isOn:Binding(get:{h.prefs.lock},set:{enabled in if enabled && !store.canLock(){store.message="فعّل قفل iPhone أولًا"}else{Task{_ = await store.change{$0.prefs.lock=enabled};if enabled{store.unlocked=true}}}}));Hint("البيانات مشفرة بمفتاح محفوظ في Keychain. تُحجب معاينة التطبيق والتسجيل المرئي؛ iOS لا يتيح منع لقطة الشاشة العادية.")}};MewCard{VStack(alignment:.leading,spacing:12){Text("التنبيهات").font(.headline);Button("تفعيل تذكير الفواتير"){Task{store.message=await Reminders.enable(store.data)}};Button("فتح إعدادات iPhone"){if let u=URL(string:UIApplication.openSettingsURLString){UIApplication.shared.open(u)}};Hint("تذكير محلي بلا تفاصيل مالية. تُجدول حتى 60 يومًا ويجددها فتح التطبيق؛ الإذن والوقت يخضعان لإعدادات النظام")}};NavigationLink("النسخ الاحتياطي والاستعادة والتقارير"){BackupView(period:period)};Hint("Mew 1.0 • محلي دون مزامنة تلقائية أو اتصال بالبنك")}.onAppear{salary=h.prefs.salaryDay}}}
}
struct ByteDocument:FileDocument {
    static var readableContentTypes:[UTType]{[.data,.pdf,.commaSeparatedText]};var bytes:Data
    init(_ data:Data){bytes=data};init(configuration:ReadConfiguration)throws{bytes=configuration.file.regularFileContents ?? Data()};func fileWrapper(configuration:WriteConfiguration)throws->FileWrapper{FileWrapper(regularFileWithContents:bytes)}
}
struct BackupView:View {
    @EnvironmentObject var store:Store;var period:Cycle
    @State var password="";@State var importing=false;@State var exporting=false;@State var document=ByteDocument(Data());@State var contentType=UTType.data;@State var filename="Mew.hbb";@State var reportKind="";@State var warning=false;@State var undo=false
    var body:some View{Page{Text("نسخة احتياطية وتقارير").font(.title.bold());MewCard{VStack(alignment:.leading,spacing:12){Text("نسخة مشفرة بكلمة مرور").font(.headline);SecureField("كلمة المرور — 8 أحرف على الأقل",text:$password).textFieldStyle(.roundedBorder).accessibilityIdentifier("backup-password");Hint("ملف HBB متوافق مع Android. احتفظ بكلمة المرور؛ لا توجد خدمة لاستعادتها.");Button("حفظ نسخة مشفرة"){Task{guard let h=store.data,let repo=store.repository else{return};do{document=ByteDocument(try await repo.exportBackup(h,password:password));password="";contentType = .data;filename="Mew-"+Dates.today()+".hbb";exporting=true}catch{store.message=error.localizedDescription}}}.disabled(store.data==nil || store.busy);Button("اختيار نسخة للاستعادة"){importing=true}.disabled(store.busy);Button("الرجوع لنسخة الأمان السابقة"){undo=true}.disabled(store.data==nil);Hint("الاستعادة تستبدل البيانات دون دمج بعد عرض ملخص وتأكيد. احفظ نسخة قبل نقل الهاتف أو حذف التطبيق.")}}
        if store.data != nil{MewCard{VStack(alignment:.leading,spacing:12){Text("تقرير الدورة المختارة").font(.headline);Hint(period.start+" إلى "+Dates.add(period.end,days:-1));Button("تصدير CSV"){reportKind="csv";warning=true};Button("تصدير PDF"){reportKind="pdf";warning=true};Hint("التقارير غير مشفرة وليست بديلًا عن النسخة الاحتياطية")}}}
    }.fileExporter(isPresented:$exporting,document:document,contentType:contentType,defaultFilename:filename){result in switch result{case .success:store.message="تم تصدير الملف";case .failure:store.message="تعذر التصدير؛ اختر مكانًا صالحًا"};document=ByteDocument(Data())}
    .fileImporter(isPresented:$importing,allowedContentTypes:[.data],allowsMultipleSelection:false){result in switch result{case .success(let urls):guard let url=urls.first else{return};let secret=password;password="";Task{let opened=url.startAccessingSecurityScopedResource();defer{if opened{url.stopAccessingSecurityScopedResource()}};do{let size=try url.resourceValues(forKeys:[.fileSizeKey]).fileSize ?? 0;try require(size<=BackupCrypto.maxSize,"النسخة أكبر من 32 ميجابايت");let bytes=try Data(contentsOf:url);await store.inspect(bytes,password:secret)}catch{store.message=error.localizedDescription}};case .failure:store.message="لم يتم اختيار نسخة؛ لم تتغير البيانات"}}
    .alert("تصدير بيانات مالية غير مشفرة",isPresented:$warning){Button("اختيار مكان الحفظ"){guard let h=store.data else{return};document=ByteDocument(reportKind=="csv" ? Reports.csv(h,period):PDFReport.make(h,period));contentType=reportKind=="csv" ? .commaSeparatedText:.pdf;filename="Mew-"+period.start+(reportKind=="csv" ? ".csv":".pdf");exporting=true};Button("إلغاء",role:.cancel){}}message:{Text("اختر مكانًا تثق به؛ الملف يحتوي تفاصيل الحسابات")}
    .alert("استبدال البيانات الحالية؟",isPresented:Binding(get:{store.restorePreview != nil},set:{if !$0{store.restorePreview=nil}})){Button("استعادة",role:.destructive){Task{await store.restore()}};Button("إلغاء",role:.cancel){store.restorePreview=nil}}message:{if let h=store.restorePreview{Text("\(h.accounts.count) حساب • \(h.transactions.count) عملية • \(h.plans.count) خطة. ستبقى إعدادات قفل هذا الهاتف، وستُحفظ نسخة أمان قبل الاستبدال.")}}
    .alert("الرجوع للبيانات السابقة؟",isPresented:$undo){Button("الرجوع",role:.destructive){Task{await store.undoRestore()}};Button("إلغاء",role:.cancel){}}message:{Text("ستُستبدل البيانات الحالية بنسخة الأمان قبل آخر استعادة؛ احفظ نسخة من العمليات الجديدة أولًا")}
    }
}
struct SearchView:View {
    @EnvironmentObject var store:Store;var open:(EditorRoute)->Void;var navigate:(String)->Void
    @State var query=""
    var body:some View{Page{Text("ابحث في بيتك").font(.title.bold());TextField("تصنيف، مبلغ، حساب، موعد أو إجراء",text:$query).textFieldStyle(.roundedBorder).accessibilityIdentifier("global-search");if let h=store.data{let hits=Search.hits(h,query:query);if hits.isEmpty{Hint(query.isEmpty ? "جرّب: الطعام، 100.00، أو نسخة احتياطية":"لا توجد نتائج مطابقة")};ForEach(hits){hit in Button{switch hit.kind{case "transaction":open(EditorRoute(kind:"transaction",transaction:h.transactions.first{$0.id==hit.id}));case "due":open(EditorRoute(kind:"due",due:h.dues.first{$0.id==hit.id}));case "account":open(EditorRoute(kind:"account",account:h.accounts.first{$0.id==hit.id}));case "category":open(EditorRoute(kind:"category",category:h.categories.first{$0.id==hit.id}));default:navigate(hit.id)}}label:{MewCard{VStack(alignment:.leading,spacing:8){Text(hit.title).font(.headline);Hint(hit.detail)}}}.buttonStyle(.plain)}}}.navigationTitle("البحث")}
}
