import XCTest
import CryptoKit
@testable import MewCore
final class CoreTests: XCTestCase {
    func fixture() -> Household { var h=Household(); h.accounts=[Account(id:"cash",name:"نقد",opening:200000),Account(id:"bank",name:"بنك")]; h.prefs.ready=true; h.prefs.salaryDay=1; h.prefs.trackingStart="2020-01-01"; h.prefs.defaultAccount="cash"; return h }
    func tx(_ type: TxType, _ amount: Int64, id: String = uid(), date: String = "2026-01-03", category: String? = "expense-0") -> Transaction { Transaction(id:id,type:type,amount:amount,date:date,accountId:"cash",destinationId:type == .transfer ? "bank":nil,categoryId:type == .transfer ? nil:category) }
    func testMoneyArabicAndLimits() throws { XCTAssertEqual(try Finance.money("١٢٣٫٤٥"),12345); XCTAssertEqual(try Finance.money("۱۲.۳"),1230); XCTAssertEqual(try Finance.money("0"),0); for input in ["-1","1,000","1.234","NaN","1000000000.01","99999999999999999999999"] { XCTAssertThrowsError(try Finance.money(input)) } }
    func testCycleAnchorsAndComparison() { XCTAssertEqual(Finance.cycle("2024-02-29",day:31),Cycle(start:"2024-02-29",end:"2024-03-31")); XCTAssertEqual(Finance.cycle("2026-02-27",day:31).start,"2026-01-31"); let p=Finance.cycle("2026-03-15",day:1); let w=Finance.comparison(p,asOf:"2026-03-15",day:1); XCTAssertEqual(w[0].days,15); XCTAssertEqual(w[0].days,w[1].days) }
    func testDatesInvalid() { for s in ["2026-02-30","2026-13-01","2026-00-01","2026-1-01","2026-01-00"] { XCTAssertThrowsError(try Dates.parse(s)) } }
    func testTransferRefundAndOpeningExcluded() throws { var h=fixture(); let expense=tx(.expense,35000,id:"expense"); var refund=tx(.refund,5000); refund.originalId=expense.id; h.transactions=[tx(.income,150000,category:"salary"),expense,tx(.transfer,50000),refund]; _=try h.validated(); let p=h.cycle("2026-01-10"); XCTAssertEqual(Finance.income(h.transactions,p),150000); XCTAssertEqual(Finance.expense(h.transactions,p),30000); XCTAssertEqual(h.balance(h.accounts[0]),270000); XCTAssertEqual(h.balance(h.accounts[1]),50000) }
    func testReferentialAndRefundValidation() throws { var h=fixture(); var t=tx(.expense,100,id:"original"); h.transactions=[t]; _=try h.validated(); var refund=tx(.refund,101); refund.originalId=t.id; h.transactions.append(refund); XCTAssertThrowsError(try h.validated()); h.transactions=[t]; t.accountId="missing"; h.transactions=[t]; XCTAssertThrowsError(try h.validated()); t.accountId="cash"; t.date=Dates.add(Dates.today(),days:1); h.transactions=[t]; XCTAssertThrowsError(try h.validated()) }
    func testBillsAnchorIdempotenceAndPartialPayment() throws { var h=fixture(); h.rules=[BillRule(id:"rent",title:"الإيجار",amount:10000,categoryId:"expense-2",start:"2026-01-31")]; h=h.materialized(asOf:"2026-02-01"); XCTAssertTrue(h.dues.contains{$0.date=="2026-02-28"}); XCTAssertTrue(h.dues.contains{$0.date=="2026-03-31"}); XCTAssertEqual(h,h.materialized(asOf:"2026-02-01")); var t=tx(.expense,3000,date:"2026-01-31",category:"expense-2"); t.dueId=h.dues[0].id; h.transactions=[t]; _=try h.validated(); XCTAssertEqual(h.remaining(h.dues[0]),7000); h.transactions[0].amount=10001; XCTAssertThrowsError(try h.validated()) }
    func testForecastAndSimulationDoNotMutate() throws { var h=fixture(); h.transactions=[tx(.expense,10000)]; let p=h.cycle("2026-01-07"); XCTAssertNil(Finance.forecast(h.transactions,p,tracking:"2026-01-03",asOf:"2026-01-07",outstanding:0)); let a=Analytics(data:h,period:p,asOf:"2026-01-10"); XCTAssertEqual(a.forecast,31000); XCTAssertEqual(a.simulate("expense-0",reduction:10).saving,1000); XCTAssertEqual(h.transactions.count,1) }
    func testSignalsAndSearchArabic() { var h=fixture(); h.transactions=[tx(.expense,10000),tx(.expense,10000)]; XCTAssertEqual(Analytics(data:h,period:h.cycle("2026-01-03"),asOf:"2026-01-03").signals.count,1); XCTAssertFalse(Search.hits(h,query:"الطَّعام ١٠٠.٠٠").isEmpty); XCTAssertTrue(Search.hits(h,query:" ").isEmpty) }
    func testEncryptedBackupRoundTripAndTamper() throws { let h=fixture(); let b=try BackupCrypto.encode(h,password:"اختبار12345"); XCTAssertEqual(try BackupCrypto.decode(b,password:"اختبار12345"),h); XCTAssertThrowsError(try BackupCrypto.decode(b,password:"incorrect")); var corrupt=b; corrupt[corrupt.count-1]^=1; XCTAssertThrowsError(try BackupCrypto.decode(corrupt,password:"اختبار12345")); XCTAssertThrowsError(try BackupCrypto.encode(h,password:"short")); XCTAssertFalse(String(data:b,encoding:.utf8)?.contains("accounts") ?? false) }
    func testEncryptedRepositoryRestoreUndoAndFailedCommit() async throws { let dir=FileManager.default.temporaryDirectory.appendingPathComponent(uid()); defer { try? FileManager.default.removeItem(at:dir) }; let key=SymmetricKey(size:.bits256); let repo=try Repository(directory:dir,key:key); var h=fixture(); try await repo.save(h); let reopened=try Repository(directory:dir,key:key); let loaded=try await reopened.load(); XCTAssertEqual(loaded,h); var invalid=h; invalid.transactions=[tx(.expense,0)]; do { try await repo.save(invalid); XCTFail("accepted zero") } catch {} ; let unchanged=try await repo.load(); XCTAssertEqual(unchanged,h); var incoming=h; incoming.accounts[0].opening=1234; incoming.prefs.lock=true; h.prefs.lock=false; let restored=try await repo.restore(incoming,current:h); XCTAssertFalse(restored.prefs.lock); XCTAssertEqual(restored.accounts[0].opening,1234); let undo=try await repo.undoRestore(); XCTAssertEqual(undo,h); let bytes=try Data(contentsOf:dir.appendingPathComponent("house.vault")); XCTAssertNil(String(data:bytes,encoding:.utf8)); var broken=bytes; broken[10]^=1; try broken.write(to:dir.appendingPathComponent("house.vault")); do { _=try await repo.load(); XCTFail("accepted corruption") } catch {}; XCTAssertTrue(FileManager.default.fileExists(atPath:dir.appendingPathComponent("house.vault").path)) }
    func testPlansAndTemplatesNeverPostAutomatically() throws { var h=fixture(); h.plans=[MonthlyPlan(period:"2026-01-01",income:100000,variable:50000,commitments:20000,saving:10000,reserve:10000,incomeDate:"2026-01-25")]; h.templates=[QuickTemplate(title:"قهوة",amount:5000,accountId:"cash",categoryId:"expense-0")]; _=try h.validated(); XCTAssertEqual(h.transactions.count,0); XCTAssertNotEqual(h.templates[0].draft().id,h.templates[0].draft().id); h.accounts[0].archived=true; h.prefs.defaultAccount="bank"; XCTAssertFalse(h.templateAvailable(h.templates[0])) }
    func testCSVInjectionAndUnicode() { var h=fixture(); var t=tx(.expense,100); t.note="=HYPERLINK(\"x\")"; h.transactions=[t]; let text=String(data:Reports.csv(h,h.cycle("2026-01-03")),encoding:.utf8)!; XCTAssertTrue(text.contains("'=HYPERLINK")); XCTAssertTrue(text.hasPrefix("\u{FEFF}")); XCTAssertTrue(text.contains("الطعام")) }
    func testJavaBackupInteroperability() throws { let url=Bundle.module.url(forResource:"android-backup",withExtension:"hbb",subdirectory:"Fixtures")!; let h=try BackupCrypto.decode(Data(contentsOf:url),password:"Mew-Test-123"); XCTAssertEqual(h.accounts.first?.name,"نقد تجريبي"); XCTAssertEqual(h.transactions.first?.amount,12345); let back=try BackupCrypto.encode(h,password:"Mew-Test-123"); let target=URL(fileURLWithPath:ProcessInfo.processInfo.environment["MEW_INTEROP_OUTPUT"] ?? "/tmp/mew-swift-backup.hbb"); try back.write(to:target) }
    func testAndroidFinanceGoldenVectors() throws { let url=Bundle.module.url(forResource:"finance-vectors",withExtension:"json",subdirectory:"Fixtures")!; struct Vector: Decodable { var date:String;var day:Int;var start:String;var end:String }; let rows=try JSONDecoder().decode([Vector].self,from:Data(contentsOf:url)); for v in rows { XCTAssertEqual(Finance.cycle(v.date,day:v.day),Cycle(start:v.start,end:v.end)) }; XCTAssertGreaterThan(rows.count,1000) }
}
